### ISSUE TITLE
新手問，import py和 from py import *是否有分別?

### ISSUE THREAD

**Issue by hkkhchan** [djangoStudyTeam/DjangoBlog#56]
謝謝

**Comment by bdbai** [comment]
前者把 `py` 这个模块引入进来，用 `py.xxx` 调用内部成员；后者把 `py`__内部__模块全部引入进来。

但我这里只能 `import py`，`from py import *` 报错，有大神解释一下么 :)
```python
>>> from py import *
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/py/_apipkg.py", line 118, in __makeattr
    modpath, attrname = self.__map__[name]
KeyError: 'test.collect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/py/_apipkg.py", line 123, in __makeattr
    raise AttributeError(name)
AttributeError: test.collect
>>> imoprt py
  File "<stdin>", line 1
    imoprt py
            ^
SyntaxError: invalid syntax
```
